#!/bin/bash

DATADIR="/var/lib/postgresql/9.3/main"
CONF="/etc/postgresql/9.3/main/postgresql.conf"
POSTGRES="/usr/local/pgsql/bin/postgres"
INITDB="/usr/local/pgsql/bin/initdb"

# test if DATADIR is existent
if [ ! -d $DATADIR ]; then
  echo "Creating Postgres data at $DATADIR"
  mkdir -p $DATADIR
fi

# test if DATADIR has content
if [ ! "$(ls -A $DATADIR)" ]; then
  echo "Initializing Postgres Database at $DATADIR"
  $INITDB $DATADIR
  $POSTGRES --single -D $DATADIR -c config_file=$CONF" <<< "CREATE USER 'puppetdb' WITH SUPERUSER PASSWORD 'Iba6gai7Coosoh2i';
fi

trap "echo \"Sending SIGTERM to postgres\"; killall -s SIGTERM postgres" SIGTERM

sh -c "$POSTGRES -D $DATADIR -c config_file=$CONF" &

wait $!

